version: 2
state_machine:
  - review
  - verified
  - canary
  - production
services:
  "1688":
    {state: verified, enabled: false, attestation: {status: pending}}
  cainiao:
    {state: verified, enabled: false, attestation: {status: pending}}
  dingding:
    {state: canary, enabled: true, attestation: {status: pending}}
  qqmail:
    {state: verified, enabled: false, attestation: {status: pending}}
  qqmusic:
    {state: verified, enabled: false, attestation: {status: pending}}
  taobao:
    {state: verified, enabled: false, attestation: {status: pending}}
  tencentcloud:
    {state: verified, enabled: false, attestation: {status: pending}}
  tmall:
    {state: verified, enabled: false, attestation: {status: pending}}
